name: savvy_bee_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.11.2+1
  cloud_firestore: ^6.1.0
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  dio: ^5.4.1
  encrypt: ^5.0.3
  file_picker: ^10.3.3
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  go_router: ^13.2.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  mime: ^2.0.0
  mono_connect: ^2.1.0
  readmore: ^3.0.0
  riverpod: ^2.6.1
  scroll_indicator: ^0.0.3
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - .env
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/images/illustrations/
    - assets/images/illustrations/avatars/
    - assets/images/other/
    - assets/icons/
    - assets/data/courses/

  fonts:
    - family: Excon
      fonts:
        - asset: assets/fonts/excon/Excon-Black.otf
        - asset: assets/fonts/excon/Excon-Bold.otf
        - asset: assets/fonts/excon/Excon-Medium.otf
        - asset: assets/fonts/excon/Excon-Regular.otf

    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsans/GeneralSans-Semibold.otf
        - asset: assets/fonts/generalsans/GeneralSans-Bold.otf
        - asset: assets/fonts/generalsans/GeneralSans-Medium.otf
        - asset: assets/fonts/generalsans/GeneralSans-Regular.otf

    - family: Neulis Neue
      fonts:
        - asset: assets/fonts/neulis/Neulis-Neue-Black.otf
        - asset: assets/fonts/neulis/Neulis-Neue-Bold.otf
        - asset: assets/fonts/neulis/Neulis-Neue-Medium.otf
        - asset: assets/fonts/neulis/Neulis-Neue-Regular.otf
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/Inter-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/Inter-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Inter-Black.ttf
  #         weight: 900
